"use client";

import type { Metadata } from "next";
import "./globals.css";

import { Plus_Jakarta_Sans } from "next/font/google";
import Navbar from "../components/Navbar";
import Footer from "@/components/Footer";
import { usePathname } from "next/navigation";
import { AppProvider } from "./contexts/AppContext";

const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  weight: ["200", "300", "400", "600", "500", "700"], // Specify weights as needed
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  const isDashboardPage = pathname.startsWith("/dashboard");

  return (
    <html lang="en">
      <body className={`${plusJakartaSans.className} antialiased`}>
        <div
        // style={
        //   isDashboardPage
        //     ? { display: "grid", gridTemplateRows: "auto 1fr" }
        //     : {}
        // }
        // className={`${isDashboardPage ? "min-h-screen" : ""}`}
        >
          <AppProvider>
            <Navbar />
            {children}
          </AppProvider>
        </div>
        {!isDashboardPage && <Footer />}
      </body>
    </html>
  );
}
